server:
  port: 4000
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds

# oauth2:
#   playerRedirectUrl: ""
#   adminRedirectUrl: ""
#   clientId: ""
#   clientSecret: ""
#   endpoints:
#     authUrl: "https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force"
#     tokenUrl: "https://oauth2.googleapis.com/token"
#     deviceAuthUrl: "https://oauth2.googleapis.com/device/code"
#   scopes:
#     - "https://www.googleapis.com/auth/userinfo.email"
#     - "https://www.googleapis.com/auth/userinfo.profile"
#   userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo"
#   revokeUrl: "https://accounts.google.com/o/oauth2/revoke"

aws:
  region:
  s3:
    bucket:
    accessKeyId:
    secretAccessKey: 

jwt:
  secret:

database:
  host:
  port:
  user:
  password:
  dbname:
  sslmode:
  schema:
